# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ferentin < Formula
  desc "Ferentin CLI - Secure OIDC authentication for CLI tools"
  homepage "https://www.ferentin.com"
  version "0.3.0"
  license "Proprietary"

  on_macos do
    on_intel do
      url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v0.3.0/ferentin_v0.3.0_darwin_amd64.tar.gz"
      sha256 "437d4e8c2bf1db80f4b4a01fcdb6758a37e01b6eac9403b2b0101976ab93444d"

      def install
        bin.install "ferentin"
      end
    end
    on_arm do
      url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v0.3.0/ferentin_v0.3.0_darwin_arm64.tar.gz"
      sha256 "53efef7da76d24911a71b64a6519171480c12eb4a1f0d8be579f3c5a7b4a83af"

      def install
        bin.install "ferentin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v0.3.0/ferentin_v0.3.0_linux_amd64.tar.gz"
        sha256 "66cffe97114150112e0e285e009be92d3808db35f8d0998433b877b9f6d4a30b"

        def install
          bin.install "ferentin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v0.3.0/ferentin_v0.3.0_linux_arm64.tar.gz"
        sha256 "5cdbad636a1131f6350bf7a4866bdd65d318f7846531e6bd30df6bc7bfc7e200"

        def install
          bin.install "ferentin"
        end
      end
    end
  end

  test do
    output = shell_output("#{bin}/ferentin --version")
    assert_match /\bversion v?\d+\.\d+\.\d+/, output
  end
end
