# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferentin" do
  version "3.9.2"

  on_macos do
    sha256 "be70c9e9b57699be90a07e19bc459166f16e40152170058bbacba34af651fbf9"
    url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v#{version}/ferentin_v#{version}_darwin_all.tar.gz",
        verified: "github.com/ferentin-net/ferentin-cli-dist"
  end
  on_linux do
    on_arm do
      sha256 "78e32f97d3d375ce81ba332f17e1d7df460806d0f5cf57b73da7d5b235c2907f"
      url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v#{version}/ferentin_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/ferentin-net/ferentin-cli-dist"
    end
    on_intel do
      sha256 "1bce9be1773bc9a3137a833cdadcdad6700734e5badfb3a3d50279ea7f3a59e6"
      url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v#{version}/ferentin_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/ferentin-net/ferentin-cli-dist"
    end
  end

  name "ferentin"
  desc "Ferentin CLI - Secure OIDC authentication for CLI tools"
  homepage "https://www.ferentin.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ferentin"

  # No zap stanza required
end
