# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferentin" do
  depends_on arch: :arm64
  depends_on macos: ">= :sequoia"

  version "4.4.0"

  on_macos do
    on_arm do
      sha256 "7fa80f0cd7b979222dff47eada80871313ce0886281207e19784d9f9c7a19b5a"
      url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v#{version}/ferentin_v#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6214ffd27f68c4d98eb9c616198c6efb91dae0f40feab3a27d57dfdecdd9a50c"
      url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v#{version}/ferentin_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "edd645ffb746c5b9d23c41ce7a0a649ef13974020fb341ed2edc8552f55a086e"
      url "https://github.com/ferentin-net/ferentin-cli-dist/releases/download/v#{version}/ferentin_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "ferentin"
  desc "Ferentin CLI - Secure OIDC authentication for CLI tools"
  homepage "https://www.ferentin.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ferentin"

  # No zap stanza required
end
